// Roslyn Generated //  Roslyn Analyzer
using System;
using UnityEngine;

namespace Omni.Core
{
    /// <summary>
    /// Auto-syncing a property with a Memory Pack serializer on the network.
    /// </summary>
    /// <remarks>
    /// Applies a unique identifier to a property for network synchronization.
    /// </remarks>
    [AttributeUsage(
        AttributeTargets.Property | AttributeTargets.Field,
        AllowMultiple = false,
        Inherited = true
    )]
    public class NetworkVariableAttribute : PropertyAttribute
    {
        internal byte Id { get; }
        internal bool TrackChangesInInspector { get; }

        /// <summary>
        /// Automatically or manually syncs a property on the network.
        /// </summary>
        /// <param name="trackChangesInInspector">
        /// Indicates whether the property should track changes in the inspector.
        /// Very slow operation, but useful for debugging.(Editor Only)
        /// </param>
        public NetworkVariableAttribute(bool trackChangesInInspector = false)
        {
            Id = 0; // 0 Is auto generated by the source generator.
            TrackChangesInInspector = trackChangesInInspector;
        }

        /// <summary>
        /// Automatically or manually syncs a property on the network.
        /// </summary>
        /// <param name="id">The ID of the network variable.</param>
        /// <param name="trackChangesInInspector">
        /// Indicates whether the property should track changes in the inspector.
        /// Very slow operation, but useful for debugging.(Editor Only)
        /// </param>
        public NetworkVariableAttribute(byte id, bool trackChangesInInspector = false)
        {
            Id = id;
            TrackChangesInInspector = trackChangesInInspector;
        }
    }
}
