// Roslyn Generated //  Roslyn Analyzer

using System;
using UnityEngine;

namespace Omni.Core
{
    /// <summary>
    /// An attribute used to mark a property or field for automatic network synchronization.
    /// This attribute supports features such as ownership control, equality checks, and 
    /// optional manual identifier assignment.
    /// </summary>
    /// <remarks>
    /// When applied to a property or field, this attribute allows it to synchronize its value
    /// across the network using a Memory Pack serializer. By default, ownership verification
    /// and equality checks are enabled.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event, AllowMultiple = false, Inherited = true)]
    public class NetworkVariableAttribute : PropertyAttribute
    {
        internal byte Id { get; }

        /// <summary>
        /// Gets or sets a value indicating whether the property requires client authority 
        /// for synchronization.
        /// </summary>
        /// <value>
        /// Default is <c>false</c>, meaning client authority is not required.
        /// </value>
        public bool IsClientAuthority { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether ownership is required for property synchronization.
        /// </summary>
        /// <value>
        /// Default is <c>true</c>, meaning only the owner can modify the synchronized variable.
        /// </value>
        public bool RequiresOwnership { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether equality checks should be performed before synchronizing the value.
        /// </summary>
        /// <value>
        /// Default is <c>true</c>, meaning the value is synchronized only if it has changed.
        /// </value>
        public bool CheckEquality { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether the field should be hidden in the Unity Inspector.
        /// </summary>
        /// <value>
        /// Default is <c>true</c>, meaning the field will not be visible in the Unity Inspector.
        /// </value>
        public bool HideInInspector { get; set; } = true;

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkVariableAttribute"/> class 
        /// with an automatically generated identifier.
        /// </summary>
        /// <remarks>
        /// The ID for the property or field will default to 0, and the source generator 
        /// will assign a unique value during compilation.
        /// </remarks>
        public NetworkVariableAttribute()
        {
            Id = 0; // 0 - Is auto generated by the source generator.
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkVariableAttribute"/> class 
        /// with a specified identifier.
        /// </summary>
        /// <param name="id">
        /// The unique identifier to assign to the property or field for synchronization.
        /// </param>
        /// <remarks>
        /// Use this constructor when a manual ID assignment is required instead of relying on the source generator.
        /// </remarks>
        public NetworkVariableAttribute(byte id)
        {
            Id = id;
        }
    }
}