// Roslyn Generated //  Roslyn Analyzer

using System;
using UnityEngine;

namespace Omni.Core
{
    /// <summary>
    /// Auto-syncing a property with a Memory Pack serializer on the network.
    /// </summary>
    /// <remarks>
    /// Applies a unique identifier to a property for network synchronization.
    /// </remarks>
    [AttributeUsage(
        AttributeTargets.Property | AttributeTargets.Field,
        AllowMultiple = false,
        Inherited = true
    )]
    public class NetworkVariableAttribute : PropertyAttribute
    {
        internal byte Id { get; }

        public bool isClientAuthority = false;
        public bool requiresOwnership = true;

        /// <summary>
        /// Automatically or manually syncs a property on the network.
        /// </summary>
        public NetworkVariableAttribute()
        {
            Id = 0; // 0 - Is auto generated by the source generator.
        }

        /// <summary>
        /// Automatically or manually syncs a property on the network.
        /// </summary>
        /// <param name="id">The ID of the network variable.</param>
        public NetworkVariableAttribute(byte id)
        {
            Id = id;
        }
    }
}